spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/miniproject
    hikari:
      password: 1234
      username: sa
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true



